import 'package:jp_prefecture/jp_prefecture.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('get all prefectures.', () {
    final prefectures = JpPrefecture.all.toList();

    expect(prefectures.length, 47);

    expect(prefectures[0].code, 1);
    expect(prefectures[0].name, '北海道');
    expect(prefectures[0].nameE, 'Hokkaido');
    expect(prefectures[0].nameH, 'ほっかいどう');
    expect(prefectures[0].nameK, 'ホッカイドウ');
    expect(prefectures[0].area, '北海道');
    expect(prefectures[0].type, '道');
    expect(prefectures[1].code, 2);
    expect(prefectures[1].name, '青森県');
    expect(prefectures[1].nameE, 'Aomori');
    expect(prefectures[1].nameH, 'あおもりけん');
    expect(prefectures[1].nameK, 'アオモリケン');
    expect(prefectures[1].area, '東北');
    expect(prefectures[1].type, '県');
    expect(prefectures[2].code, 3);
    expect(prefectures[2].name, '岩手県');
    expect(prefectures[2].nameE, 'Iwate');
    expect(prefectures[2].nameH, 'いわてけん');
    expect(prefectures[2].nameK, 'イワテケン');
    expect(prefectures[2].area, '東北');
    expect(prefectures[2].type, '県');
    expect(prefectures[3].code, 4);
    expect(prefectures[3].name, '宮城県');
    expect(prefectures[3].nameE, 'Miyagi');
    expect(prefectures[3].nameH, 'みやぎけん');
    expect(prefectures[3].nameK, 'ミヤギケン');
    expect(prefectures[3].area, '東北');
    expect(prefectures[3].type, '県');
    expect(prefectures[4].code, 5);
    expect(prefectures[4].name, '秋田県');
    expect(prefectures[4].nameE, 'Akita');
    expect(prefectures[4].nameH, 'あきたけん');
    expect(prefectures[4].nameK, 'アキタケン');
    expect(prefectures[4].area, '東北');
    expect(prefectures[4].type, '県');
    expect(prefectures[5].code, 6);
    expect(prefectures[5].name, '山形県');
    expect(prefectures[5].nameE, 'Yamagata');
    expect(prefectures[5].nameH, 'やまがたけん');
    expect(prefectures[5].nameK, 'ヤマガタケン');
    expect(prefectures[5].area, '東北');
    expect(prefectures[5].type, '県');
    expect(prefectures[6].code, 7);
    expect(prefectures[6].name, '福島県');
    expect(prefectures[6].nameE, 'Fukushima');
    expect(prefectures[6].nameH, 'ふくしまけん');
    expect(prefectures[6].nameK, 'フクシマケン');
    expect(prefectures[6].area, '東北');
    expect(prefectures[6].type, '県');
    expect(prefectures[7].code, 8);
    expect(prefectures[7].name, '茨城県');
    expect(prefectures[7].nameE, 'Ibaraki');
    expect(prefectures[7].nameH, 'いばらきけん');
    expect(prefectures[7].nameK, 'イバラキケン');
    expect(prefectures[7].area, '関東');
    expect(prefectures[7].type, '県');
    expect(prefectures[8].code, 9);
    expect(prefectures[8].name, '栃木県');
    expect(prefectures[8].nameE, 'Tochigi');
    expect(prefectures[8].nameH, 'とちぎけん');
    expect(prefectures[8].nameK, 'トチギケン');
    expect(prefectures[8].area, '関東');
    expect(prefectures[8].type, '県');
    expect(prefectures[9].code, 10);
    expect(prefectures[9].name, '群馬県');
    expect(prefectures[9].nameE, 'Gunma');
    expect(prefectures[9].nameH, 'ぐんまけん');
    expect(prefectures[9].nameK, 'グンマケン');
    expect(prefectures[9].area, '関東');
    expect(prefectures[9].type, '県');
    expect(prefectures[10].code, 11);
    expect(prefectures[10].name, '埼玉県');
    expect(prefectures[10].nameE, 'Saitama');
    expect(prefectures[10].nameH, 'さいたまけん');
    expect(prefectures[10].nameK, 'サイタマケン');
    expect(prefectures[10].area, '関東');
    expect(prefectures[10].type, '県');
    expect(prefectures[11].code, 12);
    expect(prefectures[11].name, '千葉県');
    expect(prefectures[11].nameE, 'Chiba');
    expect(prefectures[11].nameH, 'ちばけん');
    expect(prefectures[11].nameK, 'チバケン');
    expect(prefectures[11].area, '関東');
    expect(prefectures[11].type, '県');
    expect(prefectures[12].code, 13);
    expect(prefectures[12].name, '東京都');
    expect(prefectures[12].nameE, 'Tokyo');
    expect(prefectures[12].nameH, 'とうきょうと');
    expect(prefectures[12].nameK, 'トウキョウト');
    expect(prefectures[12].area, '関東');
    expect(prefectures[12].type, '都');
    expect(prefectures[13].code, 14);
    expect(prefectures[13].name, '神奈川県');
    expect(prefectures[13].nameE, 'Kanagawa');
    expect(prefectures[13].nameH, 'かながわけん');
    expect(prefectures[13].nameK, 'カナガワケン');
    expect(prefectures[13].area, '関東');
    expect(prefectures[13].type, '県');
    expect(prefectures[14].code, 15);
    expect(prefectures[14].name, '新潟県');
    expect(prefectures[14].nameE, 'Niigata');
    expect(prefectures[14].nameH, 'にいがたけん');
    expect(prefectures[14].nameK, 'ニイガタケン');
    expect(prefectures[14].area, '中部');
    expect(prefectures[14].type, '県');
    expect(prefectures[15].code, 16);
    expect(prefectures[15].name, '富山県');
    expect(prefectures[15].nameE, 'Toyama');
    expect(prefectures[15].nameH, 'とやまけん');
    expect(prefectures[15].nameK, 'トヤマケン');
    expect(prefectures[15].area, '中部');
    expect(prefectures[15].type, '県');
    expect(prefectures[16].code, 17);
    expect(prefectures[16].name, '石川県');
    expect(prefectures[16].nameE, 'Ishikawa');
    expect(prefectures[16].nameH, 'いしかわけん');
    expect(prefectures[16].nameK, 'イシカワケン');
    expect(prefectures[16].area, '中部');
    expect(prefectures[16].type, '県');
    expect(prefectures[17].code, 18);
    expect(prefectures[17].name, '福井県');
    expect(prefectures[17].nameE, 'Fukui');
    expect(prefectures[17].nameH, 'ふくいけん');
    expect(prefectures[17].nameK, 'フクイケン');
    expect(prefectures[17].area, '中部');
    expect(prefectures[17].type, '県');
    expect(prefectures[18].code, 19);
    expect(prefectures[18].name, '山梨県');
    expect(prefectures[18].nameE, 'Yamanashi');
    expect(prefectures[18].nameH, 'やまなしけん');
    expect(prefectures[18].nameK, 'ヤマナシケン');
    expect(prefectures[18].area, '中部');
    expect(prefectures[18].type, '県');
    expect(prefectures[19].code, 20);
    expect(prefectures[19].name, '長野県');
    expect(prefectures[19].nameE, 'Nagano');
    expect(prefectures[19].nameH, 'ながのけん');
    expect(prefectures[19].nameK, 'ナガノケン');
    expect(prefectures[19].area, '中部');
    expect(prefectures[19].type, '県');
    expect(prefectures[20].code, 21);
    expect(prefectures[20].name, '岐阜県');
    expect(prefectures[20].nameE, 'Gifu');
    expect(prefectures[20].nameH, 'ぎふけん');
    expect(prefectures[20].nameK, 'ギフケン');
    expect(prefectures[20].area, '中部');
    expect(prefectures[20].type, '県');
    expect(prefectures[21].code, 22);
    expect(prefectures[21].name, '静岡県');
    expect(prefectures[21].nameE, 'Shizuoka');
    expect(prefectures[21].nameH, 'しずおかけん');
    expect(prefectures[21].nameK, 'シズオカケン');
    expect(prefectures[21].area, '中部');
    expect(prefectures[21].type, '県');
    expect(prefectures[22].code, 23);
    expect(prefectures[22].name, '愛知県');
    expect(prefectures[22].nameE, 'Aichi');
    expect(prefectures[22].nameH, 'あいちけん');
    expect(prefectures[22].nameK, 'アイチケン');
    expect(prefectures[22].area, '中部');
    expect(prefectures[22].type, '県');
    expect(prefectures[23].code, 24);
    expect(prefectures[23].name, '三重県');
    expect(prefectures[23].nameE, 'Mie');
    expect(prefectures[23].nameH, 'みえけん');
    expect(prefectures[23].nameK, 'ミエケン');
    expect(prefectures[23].area, '関西');
    expect(prefectures[23].type, '県');
    expect(prefectures[24].code, 25);
    expect(prefectures[24].name, '滋賀県');
    expect(prefectures[24].nameE, 'Shiga');
    expect(prefectures[24].nameH, 'しがけん');
    expect(prefectures[24].nameK, 'シガケン');
    expect(prefectures[24].area, '関西');
    expect(prefectures[24].type, '県');
    expect(prefectures[25].code, 26);
    expect(prefectures[25].name, '京都府');
    expect(prefectures[25].nameE, 'Kyoto');
    expect(prefectures[25].nameH, 'きょうとふ');
    expect(prefectures[25].nameK, 'キョウトフ');
    expect(prefectures[25].area, '関西');
    expect(prefectures[25].type, '府');
    expect(prefectures[26].code, 27);
    expect(prefectures[26].name, '大阪府');
    expect(prefectures[26].nameE, 'Osaka');
    expect(prefectures[26].nameH, 'おおさかふ');
    expect(prefectures[26].nameK, 'オオサカフ');
    expect(prefectures[26].area, '関西');
    expect(prefectures[26].type, '府');
    expect(prefectures[27].code, 28);
    expect(prefectures[27].name, '兵庫県');
    expect(prefectures[27].nameE, 'Hyogo');
    expect(prefectures[27].nameH, 'ひょうごけん');
    expect(prefectures[27].nameK, 'ヒョウゴケン');
    expect(prefectures[27].area, '関西');
    expect(prefectures[27].type, '県');
    expect(prefectures[28].code, 29);
    expect(prefectures[28].name, '奈良県');
    expect(prefectures[28].nameE, 'Nara');
    expect(prefectures[28].nameH, 'ならけん');
    expect(prefectures[28].nameK, 'ナラケン');
    expect(prefectures[28].area, '関西');
    expect(prefectures[28].type, '県');
    expect(prefectures[29].code, 30);
    expect(prefectures[29].name, '和歌山県');
    expect(prefectures[29].nameE, 'Wakayama');
    expect(prefectures[29].nameH, 'わかやまけん');
    expect(prefectures[29].nameK, 'ワカヤマケン');
    expect(prefectures[29].area, '関西');
    expect(prefectures[29].type, '県');
    expect(prefectures[30].code, 31);
    expect(prefectures[30].name, '鳥取県');
    expect(prefectures[30].nameE, 'Tottori');
    expect(prefectures[30].nameH, 'とっとりけん');
    expect(prefectures[30].nameK, 'トットリケン');
    expect(prefectures[30].area, '中国');
    expect(prefectures[30].type, '県');
    expect(prefectures[31].code, 32);
    expect(prefectures[31].name, '島根県');
    expect(prefectures[31].nameE, 'Shimane');
    expect(prefectures[31].nameH, 'しまねけん');
    expect(prefectures[31].nameK, 'シマネケン');
    expect(prefectures[31].area, '中国');
    expect(prefectures[31].type, '県');
    expect(prefectures[32].code, 33);
    expect(prefectures[32].name, '岡山県');
    expect(prefectures[32].nameE, 'Okayama');
    expect(prefectures[32].nameH, 'おかやまけん');
    expect(prefectures[32].nameK, 'オカヤマケン');
    expect(prefectures[32].area, '中国');
    expect(prefectures[32].type, '県');
    expect(prefectures[33].code, 34);
    expect(prefectures[33].name, '広島県');
    expect(prefectures[33].nameE, 'Hiroshima');
    expect(prefectures[33].nameH, 'ひろしまけん');
    expect(prefectures[33].nameK, 'ヒロシマケン');
    expect(prefectures[33].area, '中国');
    expect(prefectures[33].type, '県');
    expect(prefectures[34].code, 35);
    expect(prefectures[34].name, '山口県');
    expect(prefectures[34].nameE, 'Yamaguchi');
    expect(prefectures[34].nameH, 'やまぐちけん');
    expect(prefectures[34].nameK, 'ヤマグチケン');
    expect(prefectures[34].area, '中国');
    expect(prefectures[34].type, '県');
    expect(prefectures[35].code, 36);
    expect(prefectures[35].name, '徳島県');
    expect(prefectures[35].nameE, 'Tokushima');
    expect(prefectures[35].nameH, 'とくしまけん');
    expect(prefectures[35].nameK, 'トクシマケン');
    expect(prefectures[35].area, '四国');
    expect(prefectures[35].type, '県');
    expect(prefectures[36].code, 37);
    expect(prefectures[36].name, '香川県');
    expect(prefectures[36].nameE, 'Kagawa');
    expect(prefectures[36].nameH, 'かがわけん');
    expect(prefectures[36].nameK, 'カガワケン');
    expect(prefectures[36].area, '四国');
    expect(prefectures[36].type, '県');
    expect(prefectures[37].code, 38);
    expect(prefectures[37].name, '愛媛県');
    expect(prefectures[37].nameE, 'Ehime');
    expect(prefectures[37].nameH, 'えひめけん');
    expect(prefectures[37].nameK, 'エヒメケン');
    expect(prefectures[37].area, '四国');
    expect(prefectures[37].type, '県');
    expect(prefectures[38].code, 39);
    expect(prefectures[38].name, '高知県');
    expect(prefectures[38].nameE, 'Kochi');
    expect(prefectures[38].nameH, 'こうちけん');
    expect(prefectures[38].nameK, 'コウチケン');
    expect(prefectures[38].area, '四国');
    expect(prefectures[38].type, '県');
    expect(prefectures[39].code, 40);
    expect(prefectures[39].name, '福岡県');
    expect(prefectures[39].nameE, 'Fukuoka');
    expect(prefectures[39].nameH, 'ふくおかけん');
    expect(prefectures[39].nameK, 'フクオカケン');
    expect(prefectures[39].area, '九州');
    expect(prefectures[39].type, '県');
    expect(prefectures[40].code, 41);
    expect(prefectures[40].name, '佐賀県');
    expect(prefectures[40].nameE, 'Saga');
    expect(prefectures[40].nameH, 'さがけん');
    expect(prefectures[40].nameK, 'サガケン');
    expect(prefectures[40].area, '九州');
    expect(prefectures[40].type, '県');
    expect(prefectures[41].code, 42);
    expect(prefectures[41].name, '長崎県');
    expect(prefectures[41].nameE, 'Nagasaki');
    expect(prefectures[41].nameH, 'ながさきけん');
    expect(prefectures[41].nameK, 'ナガサキケン');
    expect(prefectures[41].area, '九州');
    expect(prefectures[41].type, '県');
    expect(prefectures[42].code, 43);
    expect(prefectures[42].name, '熊本県');
    expect(prefectures[42].nameE, 'Kumamoto');
    expect(prefectures[42].nameH, 'くまもとけん');
    expect(prefectures[42].nameK, 'クマモトケン');
    expect(prefectures[42].area, '九州');
    expect(prefectures[42].type, '県');
    expect(prefectures[43].code, 44);
    expect(prefectures[43].name, '大分県');
    expect(prefectures[43].nameE, 'Oita');
    expect(prefectures[43].nameH, 'おおいたけん');
    expect(prefectures[43].nameK, 'オオイタケン');
    expect(prefectures[43].area, '九州');
    expect(prefectures[43].type, '県');
    expect(prefectures[44].code, 45);
    expect(prefectures[44].name, '宮崎県');
    expect(prefectures[44].nameE, 'Miyazaki');
    expect(prefectures[44].nameH, 'みやざきけん');
    expect(prefectures[44].nameK, 'ミヤザキケン');
    expect(prefectures[44].area, '九州');
    expect(prefectures[44].type, '県');
    expect(prefectures[45].code, 46);
    expect(prefectures[45].name, '鹿児島県');
    expect(prefectures[45].nameE, 'Kagoshima');
    expect(prefectures[45].nameH, 'かごしまけん');
    expect(prefectures[45].nameK, 'カゴシマケン');
    expect(prefectures[45].area, '九州');
    expect(prefectures[45].type, '県');
    expect(prefectures[46].code, 47);
    expect(prefectures[46].name, '沖縄県');
    expect(prefectures[46].nameE, 'Okinawa');
    expect(prefectures[46].nameH, 'おきなわけん');
    expect(prefectures[46].nameK, 'オキナワケン');
    expect(prefectures[46].area, '九州');
    expect(prefectures[46].type, '県');
  });

  test('find prefectures by code.', () {
    JpPrefecture prefecture = JpPrefecture.findByCode(1);
    expect(prefecture.code, 1);
    expect(prefecture.name, '北海道');

    prefecture = JpPrefecture.findByCode(2);
    expect(prefecture.code, 2);
    expect(prefecture.name, '青森県');

    prefecture = JpPrefecture.findByCode(3);
    expect(prefecture.code, 3);
    expect(prefecture.name, '岩手県');

    prefecture = JpPrefecture.findByCode(4);
    expect(prefecture.code, 4);
    expect(prefecture.name, '宮城県');

    prefecture = JpPrefecture.findByCode(5);
    expect(prefecture.code, 5);
    expect(prefecture.name, '秋田県');

    prefecture = JpPrefecture.findByCode(6);
    expect(prefecture.code, 6);
    expect(prefecture.name, '山形県');

    prefecture = JpPrefecture.findByCode(7);
    expect(prefecture.code, 7);
    expect(prefecture.name, '福島県');

    prefecture = JpPrefecture.findByCode(8);
    expect(prefecture.code, 8);
    expect(prefecture.name, '茨城県');

    prefecture = JpPrefecture.findByCode(9);
    expect(prefecture.code, 9);
    expect(prefecture.name, '栃木県');

    prefecture = JpPrefecture.findByCode(10);
    expect(prefecture.code, 10);
    expect(prefecture.name, '群馬県');

    prefecture = JpPrefecture.findByCode(11);
    expect(prefecture.code, 11);
    expect(prefecture.name, '埼玉県');

    prefecture = JpPrefecture.findByCode(12);
    expect(prefecture.code, 12);
    expect(prefecture.name, '千葉県');

    prefecture = JpPrefecture.findByCode(13);
    expect(prefecture.code, 13);
    expect(prefecture.name, '東京都');

    prefecture = JpPrefecture.findByCode(14);
    expect(prefecture.code, 14);
    expect(prefecture.name, '神奈川県');

    prefecture = JpPrefecture.findByCode(15);
    expect(prefecture.code, 15);
    expect(prefecture.name, '新潟県');

    prefecture = JpPrefecture.findByCode(16);
    expect(prefecture.code, 16);
    expect(prefecture.name, '富山県');

    prefecture = JpPrefecture.findByCode(17);
    expect(prefecture.code, 17);
    expect(prefecture.name, '石川県');

    prefecture = JpPrefecture.findByCode(18);
    expect(prefecture.code, 18);
    expect(prefecture.name, '福井県');

    prefecture = JpPrefecture.findByCode(19);
    expect(prefecture.code, 19);
    expect(prefecture.name, '山梨県');

    prefecture = JpPrefecture.findByCode(20);
    expect(prefecture.code, 20);
    expect(prefecture.name, '長野県');

    prefecture = JpPrefecture.findByCode(21);
    expect(prefecture.code, 21);
    expect(prefecture.name, '岐阜県');

    prefecture = JpPrefecture.findByCode(22);
    expect(prefecture.code, 22);
    expect(prefecture.name, '静岡県');

    prefecture = JpPrefecture.findByCode(23);
    expect(prefecture.code, 23);
    expect(prefecture.name, '愛知県');

    prefecture = JpPrefecture.findByCode(24);
    expect(prefecture.code, 24);
    expect(prefecture.name, '三重県');

    prefecture = JpPrefecture.findByCode(25);
    expect(prefecture.code, 25);
    expect(prefecture.name, '滋賀県');

    prefecture = JpPrefecture.findByCode(26);
    expect(prefecture.code, 26);
    expect(prefecture.name, '京都府');

    prefecture = JpPrefecture.findByCode(27);
    expect(prefecture.code, 27);
    expect(prefecture.name, '大阪府');

    prefecture = JpPrefecture.findByCode(28);
    expect(prefecture.code, 28);
    expect(prefecture.name, '兵庫県');

    prefecture = JpPrefecture.findByCode(29);
    expect(prefecture.code, 29);
    expect(prefecture.name, '奈良県');

    prefecture = JpPrefecture.findByCode(30);
    expect(prefecture.code, 30);
    expect(prefecture.name, '和歌山県');

    prefecture = JpPrefecture.findByCode(31);
    expect(prefecture.code, 31);
    expect(prefecture.name, '鳥取県');

    prefecture = JpPrefecture.findByCode(32);
    expect(prefecture.code, 32);
    expect(prefecture.name, '島根県');

    prefecture = JpPrefecture.findByCode(33);
    expect(prefecture.code, 33);
    expect(prefecture.name, '岡山県');

    prefecture = JpPrefecture.findByCode(34);
    expect(prefecture.code, 34);
    expect(prefecture.name, '広島県');

    prefecture = JpPrefecture.findByCode(35);
    expect(prefecture.code, 35);
    expect(prefecture.name, '山口県');

    prefecture = JpPrefecture.findByCode(36);
    expect(prefecture.code, 36);
    expect(prefecture.name, '徳島県');

    prefecture = JpPrefecture.findByCode(37);
    expect(prefecture.code, 37);
    expect(prefecture.name, '香川県');

    prefecture = JpPrefecture.findByCode(38);
    expect(prefecture.code, 38);
    expect(prefecture.name, '愛媛県');

    prefecture = JpPrefecture.findByCode(39);
    expect(prefecture.code, 39);
    expect(prefecture.name, '高知県');

    prefecture = JpPrefecture.findByCode(40);
    expect(prefecture.code, 40);
    expect(prefecture.name, '福岡県');

    prefecture = JpPrefecture.findByCode(41);
    expect(prefecture.code, 41);
    expect(prefecture.name, '佐賀県');

    prefecture = JpPrefecture.findByCode(42);
    expect(prefecture.code, 42);
    expect(prefecture.name, '長崎県');

    prefecture = JpPrefecture.findByCode(43);
    expect(prefecture.code, 43);
    expect(prefecture.name, '熊本県');

    prefecture = JpPrefecture.findByCode(44);
    expect(prefecture.code, 44);
    expect(prefecture.name, '大分県');

    prefecture = JpPrefecture.findByCode(45);
    expect(prefecture.code, 45);
    expect(prefecture.name, '宮崎県');

    prefecture = JpPrefecture.findByCode(46);
    expect(prefecture.code, 46);
    expect(prefecture.name, '鹿児島県');

    prefecture = JpPrefecture.findByCode(47);
    expect(prefecture.code, 47);
    expect(prefecture.name, '沖縄県');

    prefecture = JpPrefecture.findByCode(0);
    expect(prefecture, null);

    prefecture = JpPrefecture.findByCode(48);
    expect(prefecture, null);

    prefecture = JpPrefecture.findByCode(null);
    expect(prefecture, null);
  });

  test('find prefectures by name.', () {
    JpPrefecture prefecture = JpPrefecture.findByName('北海道');
    expect(prefecture.code, 1);
    prefecture = JpPrefecture.findByName('北海');
    expect(prefecture.code, 1);
    prefecture = JpPrefecture.findByName('北');
    expect(prefecture.code, 1);
    prefecture = JpPrefecture.findByName('青森県');
    expect(prefecture.code, 2);
    prefecture = JpPrefecture.findByName('青森');
    expect(prefecture.code, 2);
    prefecture = JpPrefecture.findByName('青');
    expect(prefecture.code, 2);
    prefecture = JpPrefecture.findByName('岩手県');
    expect(prefecture.code, 3);
    prefecture = JpPrefecture.findByName('岩手');
    expect(prefecture.code, 3);
    prefecture = JpPrefecture.findByName('岩');
    expect(prefecture.code, 3);
    prefecture = JpPrefecture.findByName('宮城県');
    expect(prefecture.code, 4);
    prefecture = JpPrefecture.findByName('宮城');
    expect(prefecture.code, 4);
    prefecture = JpPrefecture.findByName('宮');
    expect(prefecture.code, 4);
    prefecture = JpPrefecture.findByName('秋田県');
    expect(prefecture.code, 5);
    prefecture = JpPrefecture.findByName('秋田');
    expect(prefecture.code, 5);
    prefecture = JpPrefecture.findByName('秋');
    expect(prefecture.code, 5);
    prefecture = JpPrefecture.findByName('山形県');
    expect(prefecture.code, 6);
    prefecture = JpPrefecture.findByName('山形');
    expect(prefecture.code, 6);
    prefecture = JpPrefecture.findByName('山');
    expect(prefecture.code, 6);
    prefecture = JpPrefecture.findByName('福島県');
    expect(prefecture.code, 7);
    prefecture = JpPrefecture.findByName('福島');
    expect(prefecture.code, 7);
    prefecture = JpPrefecture.findByName('福');
    expect(prefecture.code, 7);
    prefecture = JpPrefecture.findByName('茨城県');
    expect(prefecture.code, 8);
    prefecture = JpPrefecture.findByName('茨城');
    expect(prefecture.code, 8);
    prefecture = JpPrefecture.findByName('茨');
    expect(prefecture.code, 8);
    prefecture = JpPrefecture.findByName('栃木県');
    expect(prefecture.code, 9);
    prefecture = JpPrefecture.findByName('栃木');
    expect(prefecture.code, 9);
    prefecture = JpPrefecture.findByName('栃');
    expect(prefecture.code, 9);
    prefecture = JpPrefecture.findByName('群馬県');
    expect(prefecture.code, 10);
    prefecture = JpPrefecture.findByName('群馬');
    expect(prefecture.code, 10);
    prefecture = JpPrefecture.findByName('群');
    expect(prefecture.code, 10);
    prefecture = JpPrefecture.findByName('埼玉県');
    expect(prefecture.code, 11);
    prefecture = JpPrefecture.findByName('埼玉');
    expect(prefecture.code, 11);
    prefecture = JpPrefecture.findByName('埼');
    expect(prefecture.code, 11);
    prefecture = JpPrefecture.findByName('千葉県');
    expect(prefecture.code, 12);
    prefecture = JpPrefecture.findByName('千葉');
    expect(prefecture.code, 12);
    prefecture = JpPrefecture.findByName('千');
    expect(prefecture.code, 12);
    prefecture = JpPrefecture.findByName('東京都');
    expect(prefecture.code, 13);
    prefecture = JpPrefecture.findByName('東京');
    expect(prefecture.code, 13);
    prefecture = JpPrefecture.findByName('東京都');
    expect(prefecture.code, 13);
    prefecture = JpPrefecture.findByName('神奈川県');
    expect(prefecture.code, 14);
    prefecture = JpPrefecture.findByName('神奈川');
    expect(prefecture.code, 14);
    prefecture = JpPrefecture.findByName('神奈');
    expect(prefecture.code, 14);
    prefecture = JpPrefecture.findByName('神');
    expect(prefecture.code, 14);
    prefecture = JpPrefecture.findByName('新潟県');
    expect(prefecture.code, 15);
    prefecture = JpPrefecture.findByName('新潟');
    expect(prefecture.code, 15);
    prefecture = JpPrefecture.findByName('新');
    expect(prefecture.code, 15);
    prefecture = JpPrefecture.findByName('富山県');
    expect(prefecture.code, 16);
    prefecture = JpPrefecture.findByName('富山');
    expect(prefecture.code, 16);
    prefecture = JpPrefecture.findByName('富');
    expect(prefecture.code, 16);
    prefecture = JpPrefecture.findByName('石川県');
    expect(prefecture.code, 17);
    prefecture = JpPrefecture.findByName('石川');
    expect(prefecture.code, 17);
    prefecture = JpPrefecture.findByName('石');
    expect(prefecture.code, 17);
    prefecture = JpPrefecture.findByName('福井県');
    expect(prefecture.code, 18);
    prefecture = JpPrefecture.findByName('福井');
    expect(prefecture.code, 18);
    prefecture = JpPrefecture.findByName('山梨県');
    expect(prefecture.code, 19);
    prefecture = JpPrefecture.findByName('山梨');
    expect(prefecture.code, 19);
    prefecture = JpPrefecture.findByName('長野県');
    expect(prefecture.code, 20);
    prefecture = JpPrefecture.findByName('長野');
    expect(prefecture.code, 20);
    prefecture = JpPrefecture.findByName('長');
    expect(prefecture.code, 20);
    prefecture = JpPrefecture.findByName('岐阜県');
    expect(prefecture.code, 21);
    prefecture = JpPrefecture.findByName('岐阜');
    expect(prefecture.code, 21);
    prefecture = JpPrefecture.findByName('岐');
    expect(prefecture.code, 21);
    prefecture = JpPrefecture.findByName('静岡県');
    expect(prefecture.code, 22);
    prefecture = JpPrefecture.findByName('静岡');
    expect(prefecture.code, 22);
    prefecture = JpPrefecture.findByName('静');
    expect(prefecture.code, 22);
    prefecture = JpPrefecture.findByName('愛知県');
    expect(prefecture.code, 23);
    prefecture = JpPrefecture.findByName('愛知');
    expect(prefecture.code, 23);
    prefecture = JpPrefecture.findByName('愛知県');
    expect(prefecture.code, 23);
    prefecture = JpPrefecture.findByName('三重県');
    expect(prefecture.code, 24);
    prefecture = JpPrefecture.findByName('三重');
    expect(prefecture.code, 24);
    prefecture = JpPrefecture.findByName('三');
    expect(prefecture.code, 24);
    prefecture = JpPrefecture.findByName('滋賀県');
    expect(prefecture.code, 25);
    prefecture = JpPrefecture.findByName('滋賀');
    expect(prefecture.code, 25);
    prefecture = JpPrefecture.findByName('滋');
    expect(prefecture.code, 25);
    prefecture = JpPrefecture.findByName('京都府');
    expect(prefecture.code, 26);
    prefecture = JpPrefecture.findByName('京都');
    expect(prefecture.code, 26);
    prefecture = JpPrefecture.findByName('京');
    expect(prefecture.code, 26);
    prefecture = JpPrefecture.findByName('大阪府');
    expect(prefecture.code, 27);
    prefecture = JpPrefecture.findByName('大阪');
    expect(prefecture.code, 27);
    prefecture = JpPrefecture.findByName('大');
    expect(prefecture.code, 27);
    prefecture = JpPrefecture.findByName('兵庫県');
    expect(prefecture.code, 28);
    prefecture = JpPrefecture.findByName('兵庫');
    expect(prefecture.code, 28);
    prefecture = JpPrefecture.findByName('兵');
    expect(prefecture.code, 28);
    prefecture = JpPrefecture.findByName('奈良県');
    expect(prefecture.code, 29);
    prefecture = JpPrefecture.findByName('奈良');
    expect(prefecture.code, 29);
    prefecture = JpPrefecture.findByName('奈');
    expect(prefecture.code, 29);
    prefecture = JpPrefecture.findByName('和歌山県');
    expect(prefecture.code, 30);
    prefecture = JpPrefecture.findByName('和歌山');
    expect(prefecture.code, 30);
    prefecture = JpPrefecture.findByName('和歌');
    expect(prefecture.code, 30);
    prefecture = JpPrefecture.findByName('和');
    expect(prefecture.code, 30);
    prefecture = JpPrefecture.findByName('鳥取県');
    expect(prefecture.code, 31);
    prefecture = JpPrefecture.findByName('鳥取');
    expect(prefecture.code, 31);
    prefecture = JpPrefecture.findByName('鳥');
    expect(prefecture.code, 31);
    prefecture = JpPrefecture.findByName('島根県');
    expect(prefecture.code, 32);
    prefecture = JpPrefecture.findByName('島根');
    expect(prefecture.code, 32);
    prefecture = JpPrefecture.findByName('島');
    expect(prefecture.code, 32);
    prefecture = JpPrefecture.findByName('岡山県');
    expect(prefecture.code, 33);
    prefecture = JpPrefecture.findByName('岡山');
    expect(prefecture.code, 33);
    prefecture = JpPrefecture.findByName('岡');
    expect(prefecture.code, 33);
    prefecture = JpPrefecture.findByName('広島県');
    expect(prefecture.code, 34);
    prefecture = JpPrefecture.findByName('広島');
    expect(prefecture.code, 34);
    prefecture = JpPrefecture.findByName('広');
    expect(prefecture.code, 34);
    prefecture = JpPrefecture.findByName('山口県');
    expect(prefecture.code, 35);
    prefecture = JpPrefecture.findByName('山口');
    expect(prefecture.code, 35);
    prefecture = JpPrefecture.findByName('徳島県');
    expect(prefecture.code, 36);
    prefecture = JpPrefecture.findByName('徳島');
    expect(prefecture.code, 36);
    prefecture = JpPrefecture.findByName('徳');
    expect(prefecture.code, 36);
    prefecture = JpPrefecture.findByName('香川県');
    expect(prefecture.code, 37);
    prefecture = JpPrefecture.findByName('香川');
    expect(prefecture.code, 37);
    prefecture = JpPrefecture.findByName('香');
    expect(prefecture.code, 37);
    prefecture = JpPrefecture.findByName('愛媛県');
    expect(prefecture.code, 38);
    prefecture = JpPrefecture.findByName('愛媛');
    expect(prefecture.code, 38);
    prefecture = JpPrefecture.findByName('高知県');
    expect(prefecture.code, 39);
    prefecture = JpPrefecture.findByName('高知');
    expect(prefecture.code, 39);
    prefecture = JpPrefecture.findByName('高');
    expect(prefecture.code, 39);
    prefecture = JpPrefecture.findByName('福岡県');
    expect(prefecture.code, 40);
    prefecture = JpPrefecture.findByName('福岡');
    expect(prefecture.code, 40);
    prefecture = JpPrefecture.findByName('佐賀県');
    expect(prefecture.code, 41);
    prefecture = JpPrefecture.findByName('佐賀');
    expect(prefecture.code, 41);
    prefecture = JpPrefecture.findByName('佐');
    expect(prefecture.code, 41);
    prefecture = JpPrefecture.findByName('長崎県');
    expect(prefecture.code, 42);
    prefecture = JpPrefecture.findByName('長崎');
    expect(prefecture.code, 42);
    prefecture = JpPrefecture.findByName('熊本県');
    expect(prefecture.code, 43);
    prefecture = JpPrefecture.findByName('熊本');
    expect(prefecture.code, 43);
    prefecture = JpPrefecture.findByName('熊');
    expect(prefecture.code, 43);
    prefecture = JpPrefecture.findByName('大分県');
    expect(prefecture.code, 44);
    prefecture = JpPrefecture.findByName('大分');
    expect(prefecture.code, 44);
    prefecture = JpPrefecture.findByName('宮崎県');
    expect(prefecture.code, 45);
    prefecture = JpPrefecture.findByName('宮崎');
    expect(prefecture.code, 45);
    prefecture = JpPrefecture.findByName('鹿児島県');
    expect(prefecture.code, 46);
    prefecture = JpPrefecture.findByName('鹿児島');
    expect(prefecture.code, 46);
    prefecture = JpPrefecture.findByName('鹿児');
    expect(prefecture.code, 46);
    prefecture = JpPrefecture.findByName('鹿');
    expect(prefecture.code, 46);
    prefecture = JpPrefecture.findByName('沖縄県');
    expect(prefecture.code, 47);
    prefecture = JpPrefecture.findByName('沖縄');
    expect(prefecture.code, 47);
    prefecture = JpPrefecture.findByName('沖');
    expect(prefecture.code, 47);

    prefecture = JpPrefecture.findByName(null);
    expect(prefecture, null);
    prefecture = JpPrefecture.findByName('稲穂県');
    expect(prefecture, null);
  });
}
